name: Build and Deploy Services

on:
  push:
    branches: ["prod", "dev"]

permissions: write-all

jobs:
  deploy:
    env:
      TF_CLOUD_ORGANIZATION: ${{ github.repository_owner }}
      TF_API_TOKEN: ${{ secrets.TFE_TOKEN }}
    name: "Build and Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Check state of initial-deploy workflow
        id: check_state
        run: |
          echo "initial_deploy_state=$(gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/workflows/initial-deploy.yml | jq -r '.state')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Set variables
        id: setvars
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        run: |
          if [[ "${{github.base_ref}}" == "dev" || "${{github.ref}}" == "refs/heads/dev" ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi

          if [[ "${{github.base_ref}}" == "prod" || "${{github.ref}}" == "refs/heads/prod" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.setvars.outputs.environment }}

      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        id: version
        with:
          scheme: calver
          increment: patch

      - name: Create Release branch
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        with:
          branch: release-${{ steps.setvars.outputs.environment }} # The branch the action should deploy to.
          folder: . # The folder the action should deploy.

      - name: Checkout Release branch
        uses: actions/checkout@v4
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        with:
          ref: release-${{ steps.setvars.outputs.environment }}
          path: release

      - name: Build
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        run: |
          cd release
          npm install
          npm run build

      - name: Commit
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        run: |
          cd release
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Release ${{ steps.version.outputs.version }}-${{ steps.setvars.outputs.environment }}"
          git push

      - name: Create release
        uses: "actions/github-script@v6"
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        env:
          VERSION: ${{ steps.version.outputs.version }}
        with:
          github-token: "${{ github.token }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.VERSION,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.VERSION,
                target_commitish: 'release-${{ steps.setvars.outputs.environment }}'
              });
              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: Fetch workspace id
        id: fetch_workspace_id
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        run: |
          workspace_id=$(curl \
          --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
          --header "Content-Type: application/vnd.api+json" \
          --request GET \
          https://app.terraform.io/api/v2/organizations/${{ github.repository_owner }}/workspaces/${{ github.event.repository.name }}-${{ steps.setvars.outputs.environment }} | jq -r '.data.id')
          echo "workspace_id=$workspace_id" >> $GITHUB_OUTPUT

      - name: update version
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        run: |
          curl \
            --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            "https://app.terraform.io/api/v2/workspaces/${{ steps.fetch_workspace_id.outputs.workspace_id }}/vars" | jq -r '.data[] | select(.attributes.key == "VERSION") | .id' > var_id

          VAR_ID=$(cat var_id)
          curl \
            --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --request DELETE \
            https://app.terraform.io/api/v2/workspaces/${{ steps.fetch_workspace_id.outputs.workspace_id }}/vars/$VAR_ID

          cat > payload.json <<EOF
          {
            "data": {
              "type":"vars",
              "attributes": {
                "key":"VERSION",
                "value":"${{ steps.version.outputs.version }}",
                "description":"code version",
                "category":"terraform",
                "hcl":false,
                "sensitive":false
              },
              "relationships": {
                "workspace": {
                  "data": {
                    "id":"${{ steps.fetch_workspace_id.outputs.workspace_id }}",
                    "type":"workspaces"
                  }
                }
              }
            }
          }
          EOF
          curl \
          --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
          --header "Content-Type: application/vnd.api+json" \
          --request POST \
          --data @payload.json \
          https://app.terraform.io/api/v2/vars

      - uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.1.1
        id: upload
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        with:
          workspace: ${{ github.event.repository.name }}-${{ steps.setvars.outputs.environment }}
          directory: release

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.1.1
        id: apply-run
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        with:
          workspace: ${{ github.event.repository.name }}-${{ steps.setvars.outputs.environment }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          plan_only: false

      - name: Delete release branch
        continue-on-error: true
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config pull.rebase true
          resp=`git ls-remote --heads origin release-${{ steps.setvars.outputs.environment }} | wc -m | sed 's/ //g'`
          if [ $resp -gt 0 ]; then
            git push origin --delete release-${{ steps.setvars.outputs.environment }}
          fi
